### ISSUE TITLE
Notice: Undefined index: opauth

### ISSUE THREAD

**Issue by o5** [michalsvec/nette-opauth#11]
Hraju si s facebook opauth a když jsem v facebook permission dialogu dal "Cancel", dostal jsem tuhle noticu, konkrétně na [tomto](https://github.com/michalsvec/nette-opauth/blob/master/src/NetteOpauth/NetteOpauth.php#L89) řádku.

**Comment by temistokles** [comment]
In my case Google bot seems to be triggering this kind of response simply by calling /auth/callback/ with no other parameters.
